AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Photo Library Lambda Functions
Resources:
  indexPhotoFunc:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: my-s3-function-2
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./Lambda/my-s3-function
      Description: 'index photo Lambda function'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::170015019306:role/codepipeline_lambda'
      Environment:
        Variables:
          REGION: us-east-1
  searchPhotoFunc:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search-photos-2
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./Lambda/search-photos
      Description: 'search photo Lambda function'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::170015019306:role/codepipeline_lambda'
      Environment:
        Variables:
          REGION: us-east-1
