AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  Lambda1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: LFX
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./Lambda/my-s3-function
      Description: 'index photo Lambda function'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:lambda:us-east-1:170015019306:function:my-s3-function'
      Environment:
        Variables:
          REGION: us-east-1
   Lambda2:
     Type: 'AWS::Serverless::Function'
     Properties:
       FunctionName: LFX
       Handler: lambda_function.lambda_handler
       Runtime: python3.8
       CodeUri: ./Lambda/search-photos
       Description: 'search photo Lambda function'
       MemorySize: 128
       Timeout: 30
       Role: 'arn:aws:lambda:us-east-1:170015019306:function:search-photos'
       Environment:
         Variables:
           REGION: us-east-1
